spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${Google_OAuth_Client_ID}
            client-secret: ${Google_OAuth_Client_Secret}
            scope: profile, email
          kakao:
            client-id: ${Kakao_OAuth_Client_ID}
            client-secret: ${Kakao_OAuth_Client_Secret}
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
