spring:
  datasource:
    url: jdbc:mariadb://alco-db.cdi4cweas6u0.ap-northeast-2.rds.amazonaws.com:3306/alco_db?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: ${LOCAL_USERNAME}
    password: ${DEV_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        show_sql: true
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    open-in-view: false
  config:
    activate:
      on-profile: prod
    import:
      - application-jwt.yaml
      - application-oauth.yaml

#server:
#  port: 443
#  ssl:
#    enabled: true
#    key-store: bootsecurity.p12
#    key-store-password: ${SSL_KEY_PASSWORD}
#    key-store-type: PKCS12
#    key-alias: bootsecurity