spring:
  config:
    activate:
      on-profile: "local"
    import:
      - application-jwt.yaml
      - application-oauth.yaml
  datasource:
    url: jdbc:mariadb://sc-alco.cn6w8cie8wju.ap-northeast-2.rds.amazonaws.com:3306/Alco?useUnicode=true&characterEncoding=UTF-8
    username: '${MyMariaDB_Name}'
    password: '${MyMariaDB_PW}'
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

